export const CAREER_FIELDS = [
  "Teknologi",
  "Kesehatan",
  "Bisnis & Keuangan",
  "Kreatif & Media",
  "Pendidikan & Riset",
  "Pemerintahan & Hukum",
] as const;

export type CareerField = (typeof CAREER_FIELDS)[number];

export const fieldStyle: Record<CareerField, string> = {
  Teknologi: "bg-sky-50 text-sky-700 border-sky-200",
  Kesehatan: "bg-danger-tint text-danger-deep border-danger",
  "Bisnis & Keuangan": "bg-amber-50 text-amber-700 border-amber-200",
  "Kreatif & Media": "bg-violet-50 text-violet-700 border-violet-200",
  "Pendidikan & Riset": "bg-emerald-50 text-emerald-700 border-emerald-200",
  "Pemerintahan & Hukum": "bg-slate-100 text-slate-700 border-slate-200",
};

export type AlumniCity = {
  id: string;
  name: string;
  region: string;
  lat: number;
  lng: number;
  overseas?: boolean;
  hq?: boolean;
};

export const alumniCities: AlumniCity[] = [
  { id: "jakarta", name: "Jakarta", region: "DKI Jakarta", lat: -6.1979, lng: 106.8509, hq: true },
  { id: "bandung", name: "Bandung", region: "Jawa Barat", lat: -6.9175, lng: 107.6191 },
  { id: "yogyakarta", name: "Yogyakarta", region: "DI Yogyakarta", lat: -7.7956, lng: 110.3695 },
  { id: "surabaya", name: "Surabaya", region: "Jawa Timur", lat: -7.2575, lng: 112.7521 },
  { id: "denpasar", name: "Denpasar", region: "Bali", lat: -8.65, lng: 115.2167 },
  { id: "medan", name: "Medan", region: "Sumatera Utara", lat: 3.5952, lng: 98.6722 },
  { id: "palembang", name: "Palembang", region: "Sumatera Selatan", lat: -2.9761, lng: 104.7754 },
  { id: "balikpapan", name: "Balikpapan", region: "Kalimantan Timur", lat: -1.2379, lng: 116.8529 },
  { id: "makassar", name: "Makassar", region: "Sulawesi Selatan", lat: -5.1477, lng: 119.4327 },
  { id: "jayapura", name: "Jayapura", region: "Papua", lat: -2.5916, lng: 140.669 },
  { id: "singapura", name: "Singapura", region: "Singapura", lat: 1.3521, lng: 103.8198, overseas: true },
  { id: "kualalumpur", name: "Kuala Lumpur", region: "Malaysia", lat: 3.139, lng: 101.6869, overseas: true },
  { id: "tokyo", name: "Tokyo", region: "Jepang", lat: 35.6762, lng: 139.6503, overseas: true },
  { id: "amsterdam", name: "Amsterdam", region: "Belanda", lat: 52.3676, lng: 4.9041, overseas: true },
  { id: "melbourne", name: "Melbourne", region: "Australia", lat: -37.8136, lng: 144.9631, overseas: true },
];

export type CareerStop = { year: string; title: string; place: string };

export type AlumniCareer = {
  id: string;
  name: string;
  angkatan: string;
  university: string;
  role: string;
  company: string;
  cityId: string;
  field: CareerField;
  photo: string;
  linkedin: string;
  bio: string;
  path: CareerStop[];
};

export const alumniCareer: AlumniCareer[] = [
  {
    id: "a1",
    name: "Rina Handayani",
    angkatan: "2018",
    university: "Universitas Indonesia",
    role: "Senior Data Scientist",
    company: "Gojek",
    cityId: "jakarta",
    field: "Teknologi",
    photo: "https://i.pravatar.cc/800?img=5",
    linkedin: "https://www.linkedin.com/in/rinahandayani",
    bio: "Membangun model machine learning untuk layanan on-demand yang dipakai jutaan pengguna setiap hari.",
    path: [
      { year: "2018", title: "Lulus SMAN 68 Jakarta", place: "MIPA" },
      { year: "2022", title: "S1 Ilmu Komputer", place: "Universitas Indonesia · cum laude" },
      { year: "2022", title: "Data Analyst", place: "Tokopedia" },
      { year: "2025", title: "Senior Data Scientist", place: "Gojek" },
    ],
  },
  {
    id: "a2",
    name: "Bima Sakti",
    angkatan: "2015",
    university: "Universitas Indonesia",
    role: "Dokter Spesialis Anak",
    company: "RSCM Jakarta",
    cityId: "jakarta",
    field: "Kesehatan",
    photo: "https://i.pravatar.cc/800?img=1",
    linkedin: "https://www.linkedin.com/in/bimasakti",
    bio: "Menekuni kesehatan anak dan aktif dalam program imunisasi komunitas di Jakarta Pusat.",
    path: [
      { year: "2015", title: "Lulus SMAN 68 Jakarta", place: "MIPA" },
      { year: "2021", title: "S1 Kedokteran", place: "Universitas Indonesia" },
      { year: "2024", title: "Residen Ilmu Kesehatan Anak", place: "FK UI / RSCM" },
      { year: "2025", title: "Dokter Spesialis Anak", place: "RSCM Jakarta" },
    ],
  },
  {
    id: "a3",
    name: "Anisa Rahma",
    angkatan: "2019",
    university: "Universitas Gadjah Mada",
    role: "Investment Analyst",
    company: "Mandiri Capital Indonesia",
    cityId: "jakarta",
    field: "Bisnis & Keuangan",
    photo: "https://i.pravatar.cc/800?img=9",
    linkedin: "https://www.linkedin.com/in/anisarahma",
    bio: "Menganalisis peluang investasi di sektor teknologi finansial dan UMKM digital.",
    path: [
      { year: "2019", title: "Lulus SMAN 68 Jakarta", place: "MIPA" },
      { year: "2023", title: "S1 Manajemen", place: "Universitas Gadjah Mada" },
      { year: "2023", title: "Management Trainee", place: "Bank Mandiri" },
      { year: "2025", title: "Investment Analyst", place: "Mandiri Capital Indonesia" },
    ],
  },
  {
    id: "a4",
    name: "Dani Kusuma",
    angkatan: "2020",
    university: "Institut Teknologi Bandung",
    role: "Machine Learning Engineer",
    company: "TikTok",
    cityId: "singapura",
    field: "Teknologi",
    photo: "https://i.pravatar.cc/800?img=8",
    linkedin: "https://www.linkedin.com/in/danikusuma",
    bio: "Bekerja dari Singapura mengembangkan sistem rekomendasi konten untuk pasar Asia Tenggara.",
    path: [
      { year: "2020", title: "Lulus SMAN 68 Jakarta", place: "MIPA" },
      { year: "2024", title: "S1 Statistika", place: "Institut Teknologi Bandung" },
      { year: "2024", title: "Machine Learning Engineer", place: "TikTok Singapore" },
    ],
  },
  {
    id: "a5",
    name: "Fitri Handayani",
    angkatan: "2017",
    university: "Universitas Padjadjaran",
    role: "Corporate Lawyer",
    company: "HHP Law Firm",
    cityId: "jakarta",
    field: "Pemerintahan & Hukum",
    photo: "https://i.pravatar.cc/800?img=15",
    linkedin: "https://www.linkedin.com/in/fitrihandayani",
    bio: "Praktisi hukum korporasi yang mendampingi perusahaan teknologi dan startup lokal.",
    path: [
      { year: "2017", title: "Lulus SMAN 68 Jakarta", place: "IPS" },
      { year: "2021", title: "S1 Hukum", place: "Universitas Padjadjaran" },
      { year: "2022", title: "Associate", place: "HHP Law Firm (Baker McKenzie)" },
      { year: "2025", title: "Corporate Lawyer", place: "HHP Law Firm" },
    ],
  },
  {
    id: "a6",
    name: "Rizky Maulana",
    angkatan: "2016",
    university: "Universitas Negeri Jakarta",
    role: "Dosen Pendidikan Matematika",
    company: "Universitas Negeri Jakarta",
    cityId: "jakarta",
    field: "Pendidikan & Riset",
    photo: "https://i.pravatar.cc/800?img=11",
    linkedin: "https://www.linkedin.com/in/rizkymaulana",
    bio: "Meneliti pembelajaran matematika berbasis teknologi dan melatih guru-guru muda.",
    path: [
      { year: "2016", title: "Lulus SMAN 68 Jakarta", place: "MIPA" },
      { year: "2020", title: "S1 Pendidikan Matematika", place: "Universitas Negeri Jakarta" },
      { year: "2023", title: "Magister Pendidikan Matematika", place: "Universitas Negeri Jakarta" },
      { year: "2025", title: "Dosen", place: "Universitas Negeri Jakarta" },
    ],
  },
  {
    id: "a7",
    name: "Sari Dewi",
    angkatan: "2018",
    university: "Institut Teknologi Bandung",
    role: "Senior Product Designer",
    company: "Shopee",
    cityId: "jakarta",
    field: "Kreatif & Media",
    photo: "https://i.pravatar.cc/800?img=16",
    linkedin: "https://www.linkedin.com/in/saridewi",
    bio: "Merancang pengalaman belanja digital yang ramah pengguna di Asia Tenggara.",
    path: [
      { year: "2018", title: "Lulus SMAN 68 Jakarta", place: "IPS" },
      { year: "2022", title: "S1 Desain Komunikasi Visual", place: "Institut Teknologi Bandung" },
      { year: "2023", title: "Product Designer", place: "Tokopedia" },
      { year: "2025", title: "Senior Product Designer", place: "Shopee" },
    ],
  },
  {
    id: "a8",
    name: "Kevin Pratama",
    angkatan: "2019",
    university: "Institut Pertanian Bogor",
    role: "Peneliti Bioinformatika",
    company: "BRIN",
    cityId: "bandung",
    field: "Pendidikan & Riset",
    photo: "https://i.pravatar.cc/800?img=12",
    linkedin: "https://www.linkedin.com/in/kevinpratama",
    bio: "Mengolah data genom untuk riset kesehatan tropis bersama peneliti nasional.",
    path: [
      { year: "2019", title: "Lulus SMAN 68 Jakarta", place: "MIPA" },
      { year: "2023", title: "S1 Fisika", place: "Institut Pertanian Bogor" },
      { year: "2024", title: "Research Assistant", place: "BRIN" },
      { year: "2025", title: "Peneliti Bioinformatika", place: "BRIN Bandung" },
    ],
  },
  {
    id: "a9",
    name: "Nadia Kusuma",
    angkatan: "2019",
    university: "Universitas Indonesia",
    role: "Psikolog Klinis",
    company: "Klinik Tumbuh",
    cityId: "yogyakarta",
    field: "Kesehatan",
    photo: "https://i.pravatar.cc/800?img=19",
    linkedin: "https://www.linkedin.com/in/nadiakusuma",
    bio: "Mendampingi remaja dan keluarga, sekaligus mengedukasi kesehatan mental di media sosial.",
    path: [
      { year: "2019", title: "Lulus SMAN 68 Jakarta", place: "IPS" },
      { year: "2023", title: "S1 Psikologi", place: "Universitas Indonesia" },
      { year: "2025", title: "Magister Profesi Psikologi", place: "Universitas Gadjah Mada" },
      { year: "2025", title: "Psikolog Klinis", place: "Klinik Tumbuh" },
    ],
  },
  {
    id: "a10",
    name: "Fajar Ramadhan",
    angkatan: "2018",
    university: "Universitas Brawijaya",
    role: "Project Engineer",
    company: "Waskita Karya",
    cityId: "surabaya",
    field: "Teknologi",
    photo: "https://i.pravatar.cc/800?img=13",
    linkedin: "https://www.linkedin.com/in/fajarramadhan",
    bio: "Mengelola proyek infrastruktur di Jawa Timur dengan standar keselamatan kerja tinggi.",
    path: [
      { year: "2018", title: "Lulus SMAN 68 Jakarta", place: "MIPA" },
      { year: "2022", title: "S1 Teknik Sipil", place: "Universitas Brawijaya" },
      { year: "2022", title: "Site Engineer", place: "Waskita Karya" },
      { year: "2025", title: "Project Engineer", place: "Waskita Karya Surabaya" },
    ],
  },
  {
    id: "a11",
    name: "Laras Puspita",
    angkatan: "2017",
    university: "Universitas Gadjah Mada",
    role: "Diplomat",
    company: "Kementerian Luar Negeri",
    cityId: "jakarta",
    field: "Pemerintahan & Hukum",
    photo: "https://i.pravatar.cc/800?img=24",
    linkedin: "https://www.linkedin.com/in/laraspspita",
    bio: "Mengurus kerja sama bilateral Indonesia dan aktif dalam isu diplomasi publik.",
    path: [
      { year: "2017", title: "Lulus SMAN 68 Jakarta", place: "IPS" },
      { year: "2021", title: "S1 Hubungan Internasional", place: "Universitas Gadjah Mada" },
      { year: "2022", title: "CPNS Kemenlu", place: "Sekolah Dinas Luar Negeri" },
      { year: "2025", title: "Diplomat", place: "Kementerian Luar Negeri RI" },
    ],
  },
  {
    id: "a12",
    name: "Yoga Pratama",
    angkatan: "2016",
    university: "Universitas Airlangga",
    role: "Brand Manager",
    company: "Kalbe Farma",
    cityId: "palembang",
    field: "Bisnis & Keuangan",
    photo: "https://i.pravatar.cc/800?img=33",
    linkedin: "https://www.linkedin.com/in/yogapratama",
    bio: "Mengembangkan strategi pemasaran produk kesehatan untuk wilayah Sumatera bagian selatan.",
    path: [
      { year: "2016", title: "Lulus SMAN 68 Jakarta", place: "MIPA" },
      { year: "2020", title: "S1 Farmasi", place: "Universitas Airlangga" },
      { year: "2021", title: "Product Specialist", place: "Kalbe Farma" },
      { year: "2025", title: "Brand Manager", place: "Kalbe Farma Palembang" },
    ],
  },
  {
    id: "a13",
    name: "Aditya Nugroho",
    angkatan: "2014",
    university: "Institut Teknologi Bandung",
    role: "Co-Founder & CEO",
    company: "Agriverse",
    cityId: "bandung",
    field: "Bisnis & Keuangan",
    photo: "https://i.pravatar.cc/800?img=51",
    linkedin: "https://www.linkedin.com/in/adityanugroho",
    bio: "Membangun startup agritech yang menghubungkan petani Jawa Barat dengan pasar modern.",
    path: [
      { year: "2014", title: "Lulus SMAN 68 Jakarta", place: "MIPA" },
      { year: "2018", title: "S1 Teknik Industri", place: "Institut Teknologi Bandung" },
      { year: "2021", title: "Business Development", place: "Startup agritech" },
      { year: "2025", title: "Co-Founder & CEO", place: "Agriverse" },
    ],
  },
  {
    id: "a14",
    name: "Maya Anggraini",
    angkatan: "2013",
    university: "Universitas Sumatera Utara",
    role: "Pemimpin Redaksi",
    company: "Harian Waspada",
    cityId: "medan",
    field: "Kreatif & Media",
    photo: "https://i.pravatar.cc/800?img=25",
    linkedin: "https://www.linkedin.com/in/mayaanggraini",
    bio: "Memimpin ruang redaksi dan mengangkat isu pendidikan serta lingkungan di Sumatera Utara.",
    path: [
      { year: "2013", title: "Lulus SMAN 68 Jakarta", place: "IPS" },
      { year: "2017", title: "S1 Ilmu Komunikasi", place: "Universitas Sumatera Utara" },
      { year: "2018", title: "Jurnalis", place: "Harian Waspada" },
      { year: "2025", title: "Pemimpin Redaksi", place: "Harian Waspada" },
    ],
  },
  {
    id: "a15",
    name: "Tengku Alfarizi",
    angkatan: "2014",
    university: "Institut Pertanian Bogor",
    role: "Agribusiness Manager",
    company: "Wilmar International",
    cityId: "medan",
    field: "Bisnis & Keuangan",
    photo: "https://i.pravatar.cc/800?img=53",
    linkedin: "https://www.linkedin.com/in/tengkualfarizi",
    bio: "Mengelola rantai pasok komoditas pertanian berkelanjutan di kawasan Sumatera.",
    path: [
      { year: "2014", title: "Lulus SMAN 68 Jakarta", place: "MIPA" },
      { year: "2018", title: "S1 Agribisnis", place: "Institut Pertanian Bogor" },
      { year: "2019", title: "Management Trainee", place: "Wilmar International" },
      { year: "2025", title: "Agribusiness Manager", place: "Wilmar International Medan" },
    ],
  },
  {
    id: "a16",
    name: "Nurul Hidayah",
    angkatan: "2016",
    university: "Universitas Hasanuddin",
    role: "Arsitek & Founder",
    company: "Rupa Studio",
    cityId: "makassar",
    field: "Kreatif & Media",
    photo: "https://i.pravatar.cc/800?img=26",
    linkedin: "https://www.linkedin.com/in/nurulhidayah",
    bio: "Merancang bangunan publik ramah iklim dan memberdayakan talenta desain lokal Makassar.",
    path: [
      { year: "2016", title: "Lulus SMAN 68 Jakarta", place: "MIPA" },
      { year: "2020", title: "S1 Arsitektur", place: "Universitas Hasanuddin" },
      { year: "2021", title: "Junior Architect", place: "Studio arsitektur Jakarta" },
      { year: "2025", title: "Arsitek & Founder", place: "Rupa Studio Makassar" },
    ],
  },
  {
    id: "a17",
    name: "Made Arya",
    angkatan: "2015",
    university: "Universitas Udayana",
    role: "Hotel Operations Manager",
    company: "Marriott",
    cityId: "denpasar",
    field: "Bisnis & Keuangan",
    photo: "https://i.pravatar.cc/800?img=54",
    linkedin: "https://www.linkedin.com/in/madearya",
    bio: "Mengelola operasional hotel bintang lima dan mempromosikan pariwisata Bali yang berkelanjutan.",
    path: [
      { year: "2015", title: "Lulus SMAN 68 Jakarta", place: "IPS" },
      { year: "2019", title: "S1 Manajemen Perhotelan", place: "Universitas Udayana" },
      { year: "2020", title: "Front Office Supervisor", place: "Marriott Bali" },
      { year: "2025", title: "Hotel Operations Manager", place: "Marriott Denpasar" },
    ],
  },
  {
    id: "a18",
    name: "Rahmat Hidayat",
    angkatan: "2018",
    university: "Institut Teknologi Bandung",
    role: "Mining Engineer",
    company: "Pertamina Hulu",
    cityId: "balikpapan",
    field: "Teknologi",
    photo: "https://i.pravatar.cc/800?img=56",
    linkedin: "https://www.linkedin.com/in/rahmathidayat",
    bio: "Bekerja di sektor energi Kalimantan dengan fokus efisiensi dan keselamatan operasi.",
    path: [
      { year: "2018", title: "Lulus SMAN 68 Jakarta", place: "MIPA" },
      { year: "2022", title: "S1 Teknik Pertambangan", place: "Institut Teknologi Bandung" },
      { year: "2023", title: "Junior Engineer", place: "Pertamina Hulu" },
      { year: "2025", title: "Mining Engineer", place: "Pertamina Hulu Kalimantan" },
    ],
  },
  {
    id: "a19",
    name: "Yulita Wenda",
    angkatan: "2017",
    university: "Universitas Cenderawasih",
    role: "Guru & Penggerak Literasi",
    company: "Sekolah Papua Harapan",
    cityId: "jayapura",
    field: "Pendidikan & Riset",
    photo: "https://i.pravatar.cc/800?img=27",
    linkedin: "https://www.linkedin.com/in/yulitawenda",
    bio: "Mendirikan perpustakaan komunitas dan mengajar literasi digital untuk pelajar Papua.",
    path: [
      { year: "2017", title: "Lulus SMAN 68 Jakarta", place: "IPS" },
      { year: "2021", title: "S1 Pendidikan Bahasa", place: "Universitas Cenderawasih" },
      { year: "2022", title: "Guru", place: "Sekolah Papua Harapan" },
      { year: "2025", title: "Guru & Penggerak Literasi", place: "Jayapura" },
    ],
  },
  {
    id: "a20",
    name: "Sherly Tanuwijaya",
    angkatan: "2013",
    university: "Institut Teknologi Bandung",
    role: "Software Engineer",
    company: "Mercari",
    cityId: "tokyo",
    field: "Teknologi",
    photo: "https://i.pravatar.cc/800?img=31",
    linkedin: "https://www.linkedin.com/in/sherlytanuwijaya",
    bio: "Berkarier di Tokyo membangun platform marketplace global dengan tim lintas negara.",
    path: [
      { year: "2013", title: "Lulus SMAN 68 Jakarta", place: "MIPA" },
      { year: "2017", title: "S1 Teknik Informatika", place: "Institut Teknologi Bandung" },
      { year: "2019", title: "Software Engineer", place: "Startup fintech Jakarta" },
      { year: "2025", title: "Software Engineer", place: "Mercari Tokyo" },
    ],
  },
  {
    id: "a21",
    name: "Raka Pradana",
    angkatan: "2012",
    university: "TU Delft",
    role: "Water Management Researcher",
    company: "Deltares",
    cityId: "amsterdam",
    field: "Pendidikan & Riset",
    photo: "https://i.pravatar.cc/800?img=59",
    linkedin: "https://www.linkedin.com/in/rakapradana",
    bio: "Meneliti pengelolaan air dan adaptasi iklim, membawa pengalaman Indonesia ke Belanda.",
    path: [
      { year: "2012", title: "Lulus SMAN 68 Jakarta", place: "MIPA" },
      { year: "2016", title: "S1 Teknik Lingkungan", place: "Institut Teknologi Bandung" },
      { year: "2020", title: "S2 Water Management", place: "TU Delft" },
      { year: "2025", title: "Researcher", place: "Deltares Amsterdam" },
    ],
  },
  {
    id: "a22",
    name: "Amelia Putri",
    angkatan: "2016",
    university: "University of Melbourne",
    role: "Financial Analyst",
    company: "Macquarie Group",
    cityId: "melbourne",
    field: "Bisnis & Keuangan",
    photo: "https://i.pravatar.cc/800?img=34",
    linkedin: "https://www.linkedin.com/in/ameliaputri",
    bio: "Menganalisis pasar investasi Australia–Asia dan aktif di komunitas diaspora Indonesia.",
    path: [
      { year: "2016", title: "Lulus SMAN 68 Jakarta", place: "IPS" },
      { year: "2020", title: "S1 Akuntansi", place: "Universitas Indonesia" },
      { year: "2022", title: "S2 Finance", place: "University of Melbourne" },
      { year: "2025", title: "Financial Analyst", place: "Macquarie Group Melbourne" },
    ],
  },
  {
    id: "a23",
    name: "Dimas Prasetyo",
    angkatan: "2015",
    university: "Universitas Padjadjaran",
    role: "Dokter Umum",
    company: "Sunway Medical Centre",
    cityId: "kualalumpur",
    field: "Kesehatan",
    photo: "https://i.pravatar.cc/800?img=68",
    linkedin: "https://www.linkedin.com/in/dimasprasetyo",
    bio: "Berpraktik di Malaysia dan menjadi relawan pengobatan gratis untuk pekerja migran.",
    path: [
      { year: "2015", title: "Lulus SMAN 68 Jakarta", place: "MIPA" },
      { year: "2021", title: "S1 Kedokteran", place: "Universitas Padjadjaran" },
      { year: "2023", title: "Medical Officer", place: "Sunway Medical Centre" },
      { year: "2025", title: "Dokter Umum", place: "Kuala Lumpur" },
    ],
  },
];

export const alumniUniversities = Array.from(new Set(alumniCareer.map((a) => a.university)));


export const universityShortNames: Record<string, string> = {
  "Universitas Indonesia": "UI",
  "Institut Teknologi Bandung": "ITB",
  "Universitas Gadjah Mada": "UGM",
  "Universitas Padjadjaran": "Unpad",
  "Universitas Negeri Jakarta": "UNJ",
  "Institut Pertanian Bogor": "IPB",
  "Universitas Brawijaya": "UB",
  "Universitas Airlangga": "Unair",
  "Universitas Sumatera Utara": "USU",
  "Universitas Hasanuddin": "Unhas",
  "Universitas Udayana": "Unud",
  "Universitas Cenderawasih": "Uncen",
  "TU Delft": "TU Delft",
  "University of Melbourne": "Uni. Melbourne",
};

export const universityLocations: Record<string, { lat: number; lng: number }> = {
  "Universitas Indonesia": { lat: -6.36, lng: 106.827 },
  "Institut Teknologi Bandung": { lat: -6.8915, lng: 107.6107 },
  "Universitas Gadjah Mada": { lat: -7.7713, lng: 110.3777 },
  "Universitas Padjadjaran": { lat: -6.9346, lng: 107.7776 },
  "Universitas Negeri Jakarta": { lat: -6.1949, lng: 106.8828 },
  "Institut Pertanian Bogor": { lat: -6.5596, lng: 106.7255 },
  "Universitas Brawijaya": { lat: -7.9523, lng: 112.6145 },
  "Universitas Airlangga": { lat: -7.268, lng: 112.781 },
  "Universitas Sumatera Utara": { lat: 3.5653, lng: 98.6557 },
  "Universitas Hasanuddin": { lat: -5.1328, lng: 119.4877 },
  "Universitas Udayana": { lat: -8.7968, lng: 115.1732 },
  "Universitas Cenderawasih": { lat: -2.6005, lng: 140.6636 },
  "TU Delft": { lat: 52.002, lng: 4.3736 },
  "University of Melbourne": { lat: -37.7983, lng: 144.9606 },
};

export const universityLogos: Record<string, string> = {
  "Universitas Indonesia": "/assets/kampus/ui.png",
  "Institut Teknologi Bandung": "/assets/kampus/itb.png",
  "Universitas Gadjah Mada": "/assets/kampus/ugm.png",
  "Universitas Padjadjaran": "/assets/kampus/unpad.png",
  "Universitas Negeri Jakarta": "/assets/kampus/unj.png",
  "Institut Pertanian Bogor": "/assets/kampus/ipb.png",
  "Universitas Brawijaya": "/assets/kampus/ub.png",
  "Universitas Airlangga": "/assets/kampus/unair.png",
  "Universitas Sumatera Utara": "/assets/kampus/usu.png",
  "Universitas Hasanuddin": "/assets/kampus/unhas.png",
  "Universitas Udayana": "/assets/kampus/unud.png",
  "Universitas Cenderawasih": "/assets/kampus/uncen.png",
  "TU Delft": "/assets/kampus/tudelft.png",
  "University of Melbourne": "/assets/kampus/unimelb.png",
};
