export type EkskulCategory =
  | "Olahraga"
  | "Seni & Budaya"
  | "Akademik"
  | "Teknologi"
  | "Sosial"
  | "Keagamaan"
  | "Bahasa";

export interface Ekskul {
  id: string;
  name: string;
  category: EkskulCategory;
  logo: string | null;
  thumb: string | null;
  members: number;
  achievements: number;
  desc: string;
  schedule: string;
  advisor: string;
}

export const EKSKUL_CATEGORIES: EkskulCategory[] = [
  "Olahraga",
  "Seni & Budaya",
  "Akademik",
  "Teknologi",
  "Sosial",
  "Keagamaan",
  "Bahasa",
];

export const categoryColors: Record<EkskulCategory, { color: string; soft: string }> = {
  Olahraga: { color: "#FFFF00", soft: "#FFF97A" },
  "Seni & Budaya": { color: "#4FBE86", soft: "#9EE3BC" },
  Akademik: { color: "#8FE0B4", soft: "#CDF3E0" },
  Teknologi: { color: "#0B7688", soft: "#3FD3E0" },
  Sosial: { color: "#5CCB94", soft: "#A5E8C6" },
  Keagamaan: { color: "#A5E8C6", soft: "#D6F5E5" },
  Bahasa: { color: "#6FD3A0", soft: "#B9ECD3" },
};

/** Normalisasi kategori dari database/CMS: rapikan spasi & fallback ke kategori valid. */
export function normalizeEkskulCategory(value: unknown): EkskulCategory {
  const trimmed = String(value ?? "").trim();
  return (EKSKUL_CATEGORIES as readonly string[]).includes(trimmed)
    ? (trimmed as EkskulCategory)
    : "Sosial";
}

export function categoryColorFor(value: unknown): { color: string; soft: string } {
  return categoryColors[normalizeEkskulCategory(value)];
}

const LOGO_DIR = "/assets/eskul";
const THUMB_DIR = "/assets/eskul/thumbs";

export const ekskulList: Ekskul[] = [
  {
    id: "execom",
    name: "Execom",
    category: "Sosial",
    logo: `${LOGO_DIR}/execom.jpg`,
    thumb: `${THUMB_DIR}/execom.webp`,
    members: 24,
    achievements: 5,
    desc: "Tim eksekutif siswa yang mengoordinasikan berbagai acara dan program sekolah.",
    schedule: "Senin, 14.00-16.00",
    advisor: "Bu Ayu",
  },
  {
    id: "pik-r",
    name: "PIK-R",
    category: "Sosial",
    logo: `${LOGO_DIR}/pik-r.jpg`,
    thumb: `${THUMB_DIR}/pik-r.webp`,
    members: 30,
    achievements: 4,
    desc: "Pusat Informasi dan Konseling Remaja, wadah edukasi kesehatan dan konseling siswa.",
    schedule: "Rabu, 13.00-15.00",
    advisor: "Bu Siti",
  },
  {
    id: "bahasa-arab-al-quran",
    name: "Bahasa Arab & Pecinta Al-Qur'an",
    category: "Keagamaan",
    logo: `${LOGO_DIR}/bahasa-arab-al-quran.jpg`,
    thumb: `${THUMB_DIR}/bahasa-arab-al-quran.webp`,
    members: 28,
    achievements: 3,
    desc: "Pendalaman bahasa Arab serta program tahsin dan tahfidz Al-Qur'an.",
    schedule: "Jumat, 13.00-15.00",
    advisor: "Ustadzah Nabila",
  },
  {
    id: "bulutangkis",
    name: "Bulutangkis",
    category: "Olahraga",
    logo: `${LOGO_DIR}/bulutangkis.jpg`,
    thumb: `${THUMB_DIR}/bulutangkis.webp`,
    members: 20,
    achievements: 7,
    desc: "Klub bulutangkis yang rutin mengikuti turnamen antarpelajar Jakarta.",
    schedule: "Selasa & Kamis, 15.00-17.00",
    advisor: "Pak Rizky",
  },
  {
    id: "elpala",
    name: "ELPALA",
    category: "Sosial",
    logo: `${LOGO_DIR}/elpala.jpg`,
    thumb: `${THUMB_DIR}/elpala.webp`,
    members: 26,
    achievements: 5,
    desc: "Ekskul pecinta alam dengan kegiatan hiking, camping, dan konservasi lingkungan.",
    schedule: "Sabtu, 08.00-12.00",
    advisor: "Pak Galih",
  },
  {
    id: "histoloka",
    name: "Histoloka",
    category: "Akademik",
    logo: `${LOGO_DIR}/histoloka.png`,
    thumb: `${THUMB_DIR}/histoloka.webp`,
    members: 18,
    achievements: 4,
    desc: "Komunitas sejarah yang mengkaji peristiwa dan budaya melalui diskusi dan kunjungan.",
    schedule: "Rabu, 14.00-16.00",
    advisor: "Bu Kartika",
  },
  {
    id: "ivratix",
    name: "IVRATIX",
    category: "Teknologi",
    logo: `${LOGO_DIR}/ivratix.jpg`,
    thumb: `${THUMB_DIR}/ivratix.webp`,
    members: 22,
    achievements: 10,
    desc: "Tim robotika dan teknologi yang aktif di kompetisi robotik nasional.",
    schedule: "Sabtu, 08.00-12.00",
    advisor: "Pak Eko",
  },
  {
    id: "jacusie",
    name: "JACUSIE",
    category: "Akademik",
    logo: `${LOGO_DIR}/jacusie.png`,
    thumb: `${THUMB_DIR}/jacusie.webp`,
    members: 20,
    achievements: 6,
    desc: "Japanese Club SMAN 68, belajar bahasa dan budaya Jepang bersama.",
    schedule: "Jumat, 14.00-16.00",
    advisor: "Bu Nurul",
  },
  {
    id: "kir",
    name: "KIR (Karya Ilmiah Remaja)",
    category: "Akademik",
    logo: `${LOGO_DIR}/kir.jpg`,
    thumb: `${THUMB_DIR}/kir.webp`,
    members: 32,
    achievements: 15,
    desc: "Wadah penelitian siswa yang aktif mengikuti kompetisi sains tingkat nasional.",
    schedule: "Rabu, 13.00-15.00",
    advisor: "Dr. Wahyu",
  },
  {
    id: "laksmapasa",
    name: "LAKSMAPASA",
    category: "Sosial",
    logo: `${LOGO_DIR}/laksmapasa.png`,
    thumb: `${THUMB_DIR}/laksmapasa.webp`,
    members: 40,
    achievements: 7,
    desc: "Pasukan pengibar bendera dengan latihan kedisiplinan dan baris-berbaris.",
    schedule: "Senin & Jumat, 15.00-17.00",
    advisor: "Pak Budi",
  },
  {
    id: "mbrass",
    name: "MBRASS",
    category: "Seni & Budaya",
    logo: `${LOGO_DIR}/mbrass.png`,
    thumb: `${THUMB_DIR}/mbrass.webp`,
    members: 35,
    achievements: 9,
    desc: "Marching band kebanggaan sekolah yang tampil di upacara dan festival.",
    schedule: "Rabu & Sabtu, 14.00-17.00",
    advisor: "Pak Yudi",
  },
  {
    id: "pmr",
    name: "Palang Merah Remaja",
    category: "Sosial",
    logo: `${LOGO_DIR}/pmr.jpg`,
    thumb: `${THUMB_DIR}/pmr.webp`,
    members: 38,
    achievements: 5,
    desc: "Aktif dalam kegiatan sosial, donor darah, dan pelatihan pertolongan pertama.",
    schedule: "Rabu & Sabtu, 13.00-15.00",
    advisor: "Bu Siti",
  },
  {
    id: "paskibra",
    name: "Paskibra",
    category: "Sosial",
    logo: `${LOGO_DIR}/paskibra.jpg`,
    thumb: `${THUMB_DIR}/paskibra.webp`,
    members: 40,
    achievements: 8,
    desc: "Pasukan pengibar bendera yang terlatih dan disiplin untuk upacara resmi.",
    schedule: "Senin & Jumat, 15.00-17.00",
    advisor: "Pak Dedi",
  },
  {
    id: "pencak-silat",
    name: "Pencak Silat",
    category: "Olahraga",
    logo: `${LOGO_DIR}/pencak-silat.jpg`,
    thumb: `${THUMB_DIR}/pencak-silat.webp`,
    members: 16,
    achievements: 5,
    desc: "Latihan bela diri tradisional Indonesia dengan fokus pada seni dan prestasi.",
    schedule: "Sabtu, 09.00-11.00",
    advisor: "Pak Andri",
  },
  {
    id: "sie-rohani-katolik",
    name: "Sie Rohani Katolik",
    category: "Keagamaan",
    logo: `${LOGO_DIR}/sie-rohani-katolik.jpg`,
    thumb: `${THUMB_DIR}/sie-rohani-katolik.webp`,
    members: 25,
    achievements: 3,
    desc: "Kegiatan kerohanian Katolik, misa bersama, doa, dan aksi sosial.",
    schedule: "Jumat, 13.00-14.30",
    advisor: "Bu Clara",
  },
  {
    id: "srp",
    name: "Sie Rohani Protestan (SRP)",
    category: "Keagamaan",
    logo: `${LOGO_DIR}/srp.jpg`,
    thumb: `${THUMB_DIR}/srp.webp`,
    members: 22,
    achievements: 3,
    desc: "Kegiatan kerohanian Protestan, persekutuan, doa, dan pelayanan sosial.",
    schedule: "Jumat, 13.00-14.30",
    advisor: "Pak Yohanes",
  },
  {
    id: "sight-basketball",
    name: "SIGHT Basketball",
    category: "Olahraga",
    logo: `${LOGO_DIR}/sight-basketball.jpg`,
    thumb: `${THUMB_DIR}/sight-basketball.webp`,
    members: 28,
    achievements: 12,
    desc: "Tim basket sekolah yang aktif berkompetisi di turnamen pelajar Jakarta.",
    schedule: "Selasa & Kamis, 14.00-16.00",
    advisor: "Pak Fajar",
  },
  {
    id: "skylance-panahan",
    name: "Skylance (Panahan)",
    category: "Olahraga",
    logo: `${LOGO_DIR}/skylance-panahan.jpg`,
    thumb: `${THUMB_DIR}/skylance-panahan.webp`,
    members: 18,
    achievements: 6,
    desc: "Klub panahan dengan latihan rutin dan kejuaraan tingkat kota hingga nasional.",
    schedule: "Sabtu, 08.00-10.00",
    advisor: "Pak Doni",
  },
  {
    id: "solitaire",
    name: "Solitaire",
    category: "Seni & Budaya",
    logo: `${LOGO_DIR}/solitaire.png`,
    thumb: `${THUMB_DIR}/solitaire.webp`,
    members: 25,
    achievements: 6,
    desc: "Grup musik siswa yang tampil di berbagai acara sekolah dan kompetisi.",
    schedule: "Senin & Kamis, 13.00-15.00",
    advisor: "Bu Rina",
  },
  {
    id: "stars-cheerleaders",
    name: "STARS Cheerleaders",
    category: "Olahraga",
    logo: `${LOGO_DIR}/stars-cheerleaders.jpg`,
    thumb: `${THUMB_DIR}/stars-cheerleaders.webp`,
    members: 30,
    achievements: 8,
    desc: "Tim cheerleading dengan koreografi energik untuk mendukung tim sekolah.",
    schedule: "Rabu & Sabtu, 14.00-16.00",
    advisor: "Bu Maya",
  },
  {
    id: "tosla",
    name: "TOSLA",
    category: "Olahraga",
    logo: `${LOGO_DIR}/tosla.jpeg`,
    thumb: `${THUMB_DIR}/tosla.webp`,
    members: 24,
    achievements: 9,
    desc: "Tim olahraga kebanggaan sekolah yang aktif di kompetisi antarpelajar.",
    schedule: "Selasa & Jumat, 15.00-17.00",
    advisor: "Pak Rizky",
  },
  {
    id: "tracesight",
    name: "TRACESIGHT",
    category: "Olahraga",
    logo: `${LOGO_DIR}/tracesight.jpg`,
    thumb: `${THUMB_DIR}/tracesight.webp`,
    members: 22,
    achievements: 8,
    desc: "Tim olahraga yang berkompetisi di berbagai kejuaraan pelajar tingkat kota.",
    schedule: "Senin & Kamis, 15.00-17.00",
    advisor: "Pak Fajar",
  },
  {
    id: "vinapan",
    name: "VINAPAN",
    category: "Olahraga",
    logo: `${LOGO_DIR}/vinapan.png`,
    thumb: `${THUMB_DIR}/vinapan.webp`,
    members: 20,
    achievements: 6,
    desc: "Klub olahraga yang rutin berlatih dan mengikuti turnamen antarpelajar.",
    schedule: "Rabu & Jumat, 15.00-17.00",
    advisor: "Pak Andri",
  },
  {
    id: "hadroh",
    name: "Hadroh",
    category: "Keagamaan",
    logo: `${LOGO_DIR}/hadroh.jpg`,
    thumb: `${THUMB_DIR}/hadroh.webp`,
    members: 30,
    achievements: 5,
    desc: "Grup musik islami yang tampil di acara sekolah dan peringatan hari besar.",
    schedule: "Jumat, 15.00-17.00",
    advisor: "Ustadz Fikri",
  },
  {
    id: "nest-esport",
    name: "NEST (E-Sport)",
    category: "Teknologi",
    logo: `${LOGO_DIR}/nest-esport.jpg`,
    thumb: `${THUMB_DIR}/nest-esport.webp`,
    members: 24,
    achievements: 7,
    desc: "Komunitas e-sport sekolah dengan latihan rutin dan turnamen antarsekolah.",
    schedule: "Jumat, 15.00-17.00",
    advisor: "Pak Bima",
  },
  {
    id: "rohis",
    name: "Rohis",
    category: "Keagamaan",
    logo: null,
    thumb: null,
    members: 60,
    achievements: 4,
    desc: "Organisasi kerohanian Islam yang aktif dalam kegiatan keagamaan dan sosial.",
    schedule: "Jumat, 12.00-13.30",
    advisor: "Pak Hendra",
  },
];
