export const schoolData = {
  identitas: {
    nama: "SMAN 68 JAKARTA",
    namaBersih: "SMA Negeri 68 Jakarta",
    npsn: "20100199",
    sekolahId: "0B39825A-6DE4-44BC-8742-7B06129634A8",
    status: "Negeri",
    bentuk: "SMA",
    akreditasi: "A",
    skorAkreditasi: 96,
    skAkreditasi: "1857/BAN-SM/SK/2022",
    akreditasiBerlakuSampai: "2027-11-28",
    kurikulum: "Kurikulum SMA Merdeka",
    penyelenggaraan: "Pagi / 5 hari",
    tahunBerdiri: 1967,
    semesterData: "2026/2027 Gasal",
  },
  kontak: {
    alamat: "Jl. Salemba Raya No. 18, RT 3/RW 6, Senen, Jakarta Pusat 10430",
    kecamatan: "Kec. Senen",
    kota: "Kota Adm. Jakarta Pusat",
    provinsi: "Prov. D.K.I. Jakarta",
    kodePos: "10430",
    telepon: "(021) 3142929",
    teleponHref: "tel:+62213142929",
    email: "emailsman68@gmail.com",
    emailHref: "mailto:emailsman68@gmail.com",
    website: "https://sman68jkt.sch.id",
    koordinat: { lat: -6.1979, lng: 106.8509 },
    mapsUrl: "https://maps.google.com/?q=-6.1979,106.8509",
  },
  siswa: {
    total: 857,
    lakiLaki: 389,
    perempuan: 468,
    rombel: 24,
    rombelPerTingkat: 8,
    rasioPerRombel: 36,
    rasioPerGuru: 22,
  },
  ptk: {
    guru: 40,
    guruLakiLaki: 19,
    guruPerempuan: 21,
    totalPtk: 54,
    persenSertifikasi: 85,
    persenASN: 97.5,
    persenKualifikasiS1: 92.5,
  },
  sarana: {
    ruangKelas: 24,
    ruangKelasLayak: 100,
    labIpa: 3,
    labFisika: 1,
    labKimia: 1,
    labBiologi: 1,
    labBahasa: 1,
    labIps: 1,
    labKomputer: 1,
    perpustakaan: 1,
    luasTanahM2: 19200,
    dayaListrikVA: 82500,
    sumberListrik: "PLN",
    internet: "Fibre Optic + Dedicated",
    sumberAir: "Pompa",
  },
  akreditasiRiwayat: [
    { tahun: 2017, skor: 96, sk: "255/BAP-SM/DKI/2017" },
    { tahun: 2022, skor: 96, sk: "1857/BAN-SM/SK/2022" },
  ],
  intakePpdb: {
    rombel: 8,
    perKelas: 36,
    estimasiSiswa: 288,
  },
  fotoResmi: [
    { src: "/assets/sekolah/sekolah-01-gedung.jpg", alt: "Gedung SMA Negeri 68 Jakarta", kategori: "Gedung" },
    { src: "/assets/sekolah/sekolah-02-halaman.jpg", alt: "Halaman dan gerbang sekolah", kategori: "Gedung" },
    { src: "/assets/sekolah/sekolah-03-papan-nama.jpg", alt: "Papan nama SMA Negeri 68", kategori: "Gedung" },
    { src: "/assets/sekolah/sekolah-04-papan-nama-arsip.jpg", alt: "Papan nama sekolah (arsip)", kategori: "Gedung" },
    { src: "/assets/sekolah/sekolah-05-salat-berjamaah.jpg", alt: "Salat berjamaah di lapangan sekolah", kategori: "Kegiatan" },
    { src: "/assets/sekolah/sekolah-06-apel.jpg", alt: "Apel pagi siswa di lapangan", kategori: "Kegiatan" },
    { src: "/assets/sekolah/sekolah-07-presentasi-kelas.jpg", alt: "Presentasi siswa di kelas", kategori: "Kegiatan" },
    { src: "/assets/sekolah/sekolah-08-seminar-karya-ilmiah.jpg", alt: "Seminar karya ilmiah siswa", kategori: "Kegiatan" },
    { src: "/assets/sekolah/sekolah-09-pembelajaran.jpg", alt: "Pembelajaran di ruang kelas", kategori: "Kegiatan" },
    { src: "/assets/sekolah/sekolah-10-ruang-guru.jpg", alt: "Ruang guru dan tata usaha", kategori: "Gedung" },
    { src: "/assets/sekolah/sekolah-11-guru-staf.jpg", alt: "Guru dan staf SMA Negeri 68", kategori: "Guru & Staf" },
    { src: "/assets/sekolah/sekolah-12-paduan-suara.jpg", alt: "Paduan suara guru dalam acara sekolah", kategori: "Guru & Staf" },
    { src: "/assets/sekolah/sekolah-13-pentas-siswa.jpg", alt: "Pentas seni siswa di lapangan", kategori: "Kegiatan" },
    { src: "/assets/sekolah/sekolah-14-juara-duta-genre.jpg", alt: "Siswa juara Duta Genre Jakarta Pusat 2023", kategori: "Prestasi" },
    { src: "/assets/sekolah/sekolah-15-fls2n.jpg", alt: "Penampilan siswa di FLS2N tingkat nasional", kategori: "Prestasi" },
    { src: "/assets/sekolah/sekolah-16-gong.jpg", alt: "Prosesi pembukaan acara sekolah", kategori: "Kegiatan" },
  ],
  sumber: {
    nama: "Data Pokok Pendidikan, Sekolah Kita (Kemendikdasmen)",
    url: "https://sekolah.data.kemendikdasmen.go.id/profil-sekolah/0B39825A-6DE4-44BC-8742-7B06129634A8",
    api: "https://sekolah.data.kemendikdasmen.go.id/v1/sekolah-service/sekolah/full-detail/0B39825A-6DE4-44BC-8742-7B06129634A8",
    diakses: "2026-09-21",
  },
} as const;
